### Schmid factor definition

For a 3D stress state $\sigma$ (here $\sigma$ is a tensor), and a slip system $s$ composed by the normal $n^s$ to the slip plane and the slip direction $l^s$, the Schmid law can be used to compute the shear seen by the crystal in the direction $l^s$ (the resolved shear stress). First we express the stress vector applied on face $n^s$ by $\sigma. n^s$. Then we project this vector in direction $l^s$ with $\tau^s = l^s.(\sigma.n^s)=l^s_i \sigma_{ij} n^s_j$

Under a uniaxial stress state $\sigma$ the Schmid factor can be computed by $\dfrac{\tau^s}{\sigma}$:

<img src="resolved_shear_stress.png">

Compute the Schmid factor for all slip systems in (a) the octaedral slip case and (b) the basal + prismatic case. For the moment we consider only a crystal oriented 001 (cube). The loading direction is 3 (or Z).

#### Note - CR:
FCC has 12 potential slip systems. Schmid factor enables to narrow down which systems among those will actually have a chance to activate (under a given loading configuration) by computing the resolved shear stress for each slip system and compare them.

### Manual calculation

Here comes the manual calculations, the trick is not to forget to normalize the vectors.

#### results for cubic symmetry

slip systems definition

In [9]:
#We manually compute the Schmid factor for ONE slip system (1,1,1) [-1,0,1]
#Same process has to be repeated for all slip systems to know which one will have the highest probability to slip
import numpy as np
from numpy import linalg as LA

Sigma0 = 1.0
Sigma = np.array([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,Sigma0]])


Ns_Miller = np.array([1.0,1.0,1.0])
print(LA.norm(Ns_Miller))
Ns_Miller_Unit = (1/LA.norm(Ns_Miller))*Ns_Miller
print(Ns_Miller_Unit)

t_Ns = Sigma@(Ns_Miller_Unit)
print(t_Ns)

Slip_Dir = np.array([-1.0,0.0,1.0])
Slip_Dir_Unit = (1/LA.norm(Slip_Dir))*Slip_Dir
print(Slip_Dir_Unit)

Tau = Slip_Dir_Unit@t_Ns

print("Schmid factor for ONE slip system on the FCC lattice: ", Tau)

1.7320508075688772
[0.57735027 0.57735027 0.57735027]
[0.         0.         0.57735027]
[-0.70710678  0.          0.70710678]
Schmid factor for ONE slip system on the FCC lattice:  0.408248290463863


#### results for hexagonal symmetry

slip system definition

### Calculation using Pymicro

#### results for cubic symmetry

In [10]:
from pymicro.crystal.lattice import Lattice, HklPlane, HklDirection, SlipSystem
from pymicro.crystal.microstructure import Orientation

cubic = Lattice.cubic(1.0)  # here the lattice parameter is not important
s1 = SlipSystem.from_indices((1, 1, 1), (-1, 0, 1), lattice=cubic) #CR: Integers are correct for Miller indices
o_cube = Orientation.cube()
o_cube.schmid_factor(s1, load_direction=[0., 0., 1])

0.408248290463863

#### results for hexagonal symmetry

<img src="Hexagonal_Lattice_Plans_Primordiaux.png">

In [16]:
from pymicro.crystal.lattice import Lattice, HklPlane, HklDirection, SlipSystem
from pymicro.crystal.microstructure import Orientation

#CR: We consider first a basal slip system: (0,0,1,1) <1,1,-2,0> 
HEXAGON = Lattice.hexagonal(1.,1.)  #Here the lattice parameter is not important
s1 = SlipSystem.from_indices((0, 0, 1), (1, 1, 0), lattice=HEXAGON) #CR: We don't write the 3rd Miller index
o_cube = Orientation.cube() #CR: This says that we are in "cube" orientation mode of the crystal, i.e. not rotated
print ("Under load_direction=[0., 0., 1.] basal plane has no shear at all:", o_cube.schmid_factor(s1, load_direction=[0., 0., 1.]))

Under load_direction=[0., 0., 1.] basal plane has no shear at all: 0.0


In [18]:
from pymicro.crystal.lattice import Lattice, HklPlane, HklDirection, SlipSystem
from pymicro.crystal.microstructure import Orientation

#CR: We consider a pyramidal Pi1 slip system: (1,1,-2,2) <1,1,-2,3> 
HEXAGON = Lattice.hexagonal(1.,1.)  #Here the lattice parameter is not important
s1 = SlipSystem.from_indices((1, 1, 2), (1, 1, 3), lattice=HEXAGON) #CR: We don't write the 3rd Miller index
o_cube = Orientation.cube() #CR: This says that we are in "cube" orientation mode of the crystal, i.e. not rotated
print ("Under load_direction=[0., 0., 1.] pyramidal system experiences shear:", o_cube.schmid_factor(s1, load_direction=[0., 0., 1.]))

Under load_direction=[0., 0., 1.] pyramidal system experiences shear: 0.6708203932499368


### Calculation using Z-set

Run computation using z-set with the different orientations and slip systems definitions. report results here.
```
Zrun rve3d.inp
```

the stress applied is $\sigma=100$ MPa.

#### results for cubic symmetry

cube orientation (euler 0., 0., 0.)

| $\tau_1$ | $\tau_2$ | $\tau_3$ | $\tau_4$ | $\tau_5$ | $\tau_6$ | $\tau_7$ | $\tau_8$ | $\tau_9$ | $\tau_{10}$ | $\tau_{11}$ | $\tau_{12}$ |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 40.82 | 40.82 | 0.0 | 40.82 | 40.82 | 0.0 | 40.82 | 0.0 | 40.82 | 0.0 | -40.82 | -40.82 |



#### results for hexagonal symmetry